[project]
name = "ewa"
version = "0.1.0"
description = "ewa core CLI application"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic-settings>=2.12.0",
    "sqlmodel>=0.0.27",
    "typer>=0.20.0",
]

[tool.uv.workspace]
members = [
    "plugins/*",
    "library",
]

#[build-system]
#requires = ["hatchling"]
#build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ewa"]

[dependency-groups]
dev = [
    "ruff>=0.14.7",
]

[project.scripts]
ewa = "ewa.main:main"

