[project]
name = "library"
version = "0.1.0"
description = "Temporary EWA Library Package"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.optional-dependencies]
db = ["sqlitedict>=2.1.0",]
docs = ["beautifulsoup4>=4.14.2","lxml>=6.0.2","ebooklib>=0.20",]
data = ["pandas>=2.3.3",]
image = ["pillow>=12.0.0",]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/library"]